config/routes.rb
Rails.application.routes.draw do

  get 'reviews/new'

  get 'reviews/create'

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews

  mount_uploader :image, ImageUploader


  validates :title, :director, :description, :release_date, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }

  validate :release_date_is_in_the_future

  def review_average
    if reviews.any?
      reviews.sum(:rating_out_of_ten)/reviews.size
    else
      return 0
    end
  end

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      Movie.all
    end
  end

  private

  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should probably be in the future") if release_date < Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: { only_integer: true }
  validates :rating_out_of_ten, numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten, numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews

  has_secure_password

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in to access this page!"
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.search(params[:search])
    if @movies.class == Array
      @movies = Kaminari.paginate_array(@posts).page(params[:page]).per(5) 
    else
      @movies = @movies.page(params[:page]).per(5) # if @posts is AR::Relation object 
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :image, :description
      )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie
  
  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review has been successfully created!"
    else
      render :new
    end
  end

  private

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.user_id
      redirect_to movies_path
    else
      notice: "Log in failed!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Peace!"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Peace!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id #auto log in
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
 <footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted: 
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
    <% end %>

  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>

  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>

  <div>
    <%= f.label "director" %><br>
    <%= f.text_field "director" %>
  </div>

  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.text_field "runtime_in_minutes" %><br>
  </div>
  
  <div>
    <%= f.label "poster_image_url" %><br>
    <%= f.text_field "poster_image_url" %><br>
    <%= image_tag @movie.poster_image_url if @movie.poster_image_url %>
  </div>

  <div>
    <%= f.label "upload an image" %><br>
    <%= f.file_field :image %>
    <%= image_tag @movie.image_url(:thumb) if @movie.image? %>
  </div>

  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>s
  </div>

  <div>
  <%= f.submit %>
  </div>

<% end %>

app/views/movies/_movies.html.erb
<% @movies.each do |movie| %>

<style>
table, th, td {
    border: 1px solid gray;
    border-collapse: collapse;
    margin: auto;
}
th, td {
    padding-top: 5px;
    padding-bottom: 5px;
    padding-right: 10px;
    padding-left: 10px;
    text-align: left;
    font-family: Helvetica;
    font-size: 14px;
    font-style: normal;
    font-variant: normal;
    font-weight: 100;
    line-height: 15px;  
}
</style>


<table style="width:90%">
  <tr>
    <th colspan="1">Movie:</th>
    <th colspan="1">Rotten Mangoes Rating:</th>
    <th colspan="1">Release Date:</th>
    <th colspan="1">Director:</th>
    <th colspan="1">Runtime:</th>
    <th colspan="1">Plot:</th>
  </tr>
  <tr>
  <%= link_to image_tag(movie.image_url(:thumb)), movie_path(movie) %>
  <%= link_to image_tag(movie.poster_image_url), movie_path(movie) %>
  </tr>
  <tr>
  <td><%= link_to movie.title, movie_path(movie) %></td>
  <td><%= movie.review_average %>/10</td>
  <td><%= formatted_date(movie.release_date) %></td>
  <td><%= movie.director %></td>
  <td><%= movie.runtime_in_minutes %> minutes</td>
  <td><p><%= movie.description %></p></td>
</tr>
</table>

<hr>

<% end %> 

app/views/movies/edit.html.erb
<h2>Edit "<%= @movie.title %>" </h2>

<%= render 'form' %>

<hr>
<%= link_to "Back to all movies", movies_path %>

app/views/movies/index.html.erb
<style>

body {
  font-family: Helvetica;
  font-style: normal;
  font-variant: normal;
  font-weight: 100;
  text-align: center;
}

h1 {
  font-family: Helvetica;
  font-style: normal;
  font-variant: normal;
  font-weight: 100;
}

</style>

<h1> Welcome to Rotten Mangoes! </h1> 

<%= link_to "Submit a movie!", new_movie_path %> 

<hr>

Search:
<%= form_tag(movies_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Movies" %>
<%= submit_tag "Search" %>
<% end %>

<hr>



<%= render 'movies' %>


<%= paginate @movies %>
<%= page_entries_info @movies %>

app/views/movies/new.html.erb
<h2>Submit a movie!</h2> 

<%= render 'form' %>

<hr>
<%= link_to "Back to all movies", movies_path %>

app/views/movies/show.html.erb
<style>
body {
  text-align: center;
  font-family: Helvetica;
  font-style: normal;
  font-variant: normal;
  font-weight: 100;
  text-align: center;
}

h2, h3, h4 {
  font-family: Helvetica;
  font-style: normal;
  font-variant: normal;
  font-weight: 100;
}
</style>



<%= image_tag @movie.image_url(:thumb) if @movie.image? %>
<%= image_tag @movie.poster_image_url %>

<h2><%= @movie.title %> </h2> 

<h3>Release Date: <%= formatted_date(@movie.release_date) %></h3>
<h4> Director: <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes </h4>
<h4> Rotten Mangoes Rating: <%= @movie.review_average %>/10 </h4>
<p><%= @movie.description %></p>

<h5><%= link_to "Edit", edit_movie_path(@movie) %> | <%= link_to "Delete", @movie, method: :delete, data: { confirm: "Are you 100% sure?" } %> </h5>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>Review written by: <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

<%= link_to "Back to all movies", movies_path %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "text" %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label "rating_out_of_ten" %><br>
    <%= f.number_field "rating_out_of_ten" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/session/new.html.erb
<h1>Log In:</h1>

<%= form_tag sessions_path do %>

  <div>
    <%= label_tag "email" %><br>
    <%= text_field_tag "email" %>
  </div>

  <div>
    <%=label_tag :password %><br>
    <%= password_field_tag :password %>
  </div>

  <div>
    <%= submit_tag "Log In" %> 
  </div>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up:</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error")%> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div>
      <%= f.label "email" %><br>
      <%= f.text_field "email" %>
    </div>

    <div>
      <%= f.label "firstname", "First Name" %><br>
      <%= f.text_field "firstname" %>
    </div>

    <div>
      <%= f.label "lastname", "Last Name" %><br>
      <%= f.text_field "lastname" %>
    </div>

    <div>
      <%= f.label "password" %><br>
      <%= f.password_field "password" %>
    </div>

    <div>
      <%= f.label "password_confimation" %><br>
      <%= f.password_field "password_confimation" %>
    </div>

    <div>
      <%= f.submit "Submit" %>
    </div>

<% end %>